const { MongoClient } = require('mongodb');
const jwt = require('jsonwebtoken');
const fs = require('fs');

const MONGO_URI = 'mongodb+srv://kavish_31:1giExbyouRvcvUXT@cluster0.746di7e.mongodb.net/jobscheduler?retryWrites=true&w=majority&appName=Cluster0';
const JWT_SECRET = Buffer.from('oipx5qcMDbTmAy//cnOO1UQY1hSv7dPodkncf5u5Ezw=', 'utf-8');
const USERS_COUNT = 6000;
const BATCH_SIZE = 1000;

async function seed() {
    console.log(`Connecting to MongoDB...`);
    const client = new MongoClient(MONGO_URI);
    
    try {
        await client.connect();
        const db = client.db('jobscheduler');
        const usersCollection = db.collection('users');

        console.log(`Clearing existing test users...`);
        // Only delete users generated by this script to avoid deleting your real user
        await usersCollection.deleteMany({ email: { $regex: /^test_user_/ } });

        const tokens = [];
        // Add header for CSV
        tokens.push('token');

        console.log(`Generating ${USERS_COUNT} users and tokens...`);
        
        let usersToInsert = [];
        for (let i = 1; i <= USERS_COUNT; i++) {
            const email = `test_user_${i}@example.com`;
            const user = {
                name: `Test User ${i}`,
                email: email,
                password: 'dummy_hashed_password', // Doesn't matter, we bypass login API
                _class: 'com.example.JobScheduler.auth.entity.User'
            };
            usersToInsert.push(user);

            // Generate JWT for the user exactly like Spring does
            const token = jwt.sign({ sub: email }, JWT_SECRET, { expiresIn: '24h' });
            tokens.push(token);

            if (usersToInsert.length === BATCH_SIZE) {
                await usersCollection.insertMany(usersToInsert);
                console.log(`Inserted ${i} users...`);
                usersToInsert = [];
            }
        }

        // Insert remaining
        if (usersToInsert.length > 0) {
            await usersCollection.insertMany(usersToInsert);
            console.log(`Inserted ${USERS_COUNT} users...`);
        }

        // Write tokens to CSV
        console.log(`Writing tokens to tokens.csv...`);
        fs.writeFileSync('tokens.csv', tokens.join('\n'));
        console.log(`Done! Created tokens.csv with ${USERS_COUNT} tokens.`);

    } catch (err) {
        console.error('Error seeding:', err);
    } finally {
        await client.close();
    }
}

seed();
