# Load environment variables from .env file
spring.config.import=optional:file:.env

spring.application.name=JobScheduler
server.port=${SERVER_PORT:8080}

# MongoDB
spring.data.mongodb.uri=mongodb+srv://kavish_1121:ZcYO8exJOAqpqi7V@cluster0.cvw1r6l.mongodb.net/jobscheduler?retryWrites=true&w=majority&appName=Cluster0&maxPoolSize=200&minPoolSize=20&waitQueueTimeoutMS=5000
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=${JWT_SECRET:oipx5qcMDbTmAy//cnOO1UQY1hSv7dPodkncf5u5Ezw=}

# Redis Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Tomcat
server.tomcat.threads.max=800
server.tomcat.threads.min-spare=100
server.tomcat.accept-count=10000
server.tomcat.max-connections=20000
server.tomcat.connection-timeout=5000

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}